# dataset 

csv_file_path: /home/linlin/dataset/sports_kaggle/sports.csv
classes: 100
columns:
  images: filepaths 
  labels: labels 
  split: data set  # split: fold
  fold: False # 
parent_dataset_dir:  /home/linlin/dataset/sports_kaggle/
saved_label_path: ./label.json # used in api



# train  # 2 spaces

train:
  width: 224
  height: 224
  batch_size: 16
valid:
  width: 224
  height: 224
  batch_size: 16

pretrained_model_path: ./Densenet121_sports_classification.pt
saved_model_path: ./Densenet121_sports_classification.pt # used in api
learning_rate: 1e-3 
epochs: 100
numpy_test: False

tensorboard_name: mela_api 
device: cpu
numpy_test: False


# flask
API:
  upload_folder: ./static
  device: cpu
  width: 416
  height: 416 
  
onnx:
  use_onnx: True
  saved_onnx_path: ./Densenet121_sports_classification.onnx




# tensorrt 
tensorrt:
  width: 416
  height: 416
  device: cuda
  trt_model_path: ./Densenet121_sports_classification.ts